# Generated by Django 3.1.5 on 2021-03-06 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20210305_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='This user has not written anything here.', null=True),
        ),
    ]
