# Generated by Django 3.1.5 on 2021-03-06 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20210306_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/profile'),
        ),
    ]
