# Generated by Django 3.1.5 on 2021-03-06 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20210306_0429'),
        ('blog', '0020_auto_20210305_2026'),
    ]

    operations = [
    ]
