# Generated by Django 3.1.5 on 2021-03-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_merge_20210305_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='I have not write anything about myself yet', null=True),
        ),
    ]
