# Generated by Django 3.1.5 on 2021-03-07 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20210306_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='I have not written anything about myself yet', null=True),
        ),
    ]
