# Generated by Django 3.1.7 on 2021-03-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_element_heatmap_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heatmap',
            name='id',
        ),
        migrations.AlterField(
            model_name='heatmap',
            name='name',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
