# Generated by Django 3.1.7 on 2021-03-07 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20210307_0307'),
        ('blog', '0023_auto_20210306_1647'),
    ]

    operations = [
    ]
