# Generated by Django 3.1.7 on 2021-03-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20210307_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='I have not write anything about myself yet', null=True),
        ),
    ]
